apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-configmap
data: 
  nginx.conf: |
    user nginx;
    worker_processes 2;
    events {
      worker_connections 2048;
    }
    http {

      upstream app {
        server 10.244.1.17:5000 max_fails=3 fail_timeout=15s;
        server 10.244.2.16:5000 max_fails=3 fail_timeout=15s;
        server 10.244.2.18:5000 max_fails=3 fail_timeout=15s;
      }
     
      server {
        listen 80;
        server_name nginx;
          location / {
            proxy_pass http://app;
          }
      }
    }
