---

- name: Wget of Go archive
  get_url:
    url: https://storage.googleapis.com/golang/getgo/installer_linux
    dest: /root/

- name: Make a intaller executable
  shell:
    cmd: 'chmod +x /root/installer_linux'

- name: Start a installer
  shell: 
    cmd: '/root/installer_linux'

- name: Source
  shell:
    cmd: '. ~/.bash_profile'
