---

#- name: Initialization of cluster
#  command:
#    cmd: 'kubeadm init --pod-network-cidr={{pod_network_cidr}} --cri-socket={{cri_socket}}'

#- name: Export kubeconfig file
#  shell:
#    cmd: 'export KUBECONFIG=/etc/kubernetes/admin.conf'

#- name: Install network for pods
#  shell:
#    cmd: 'kubectl apply -f {{add_onn}}'

- name: Generate join command for worker nodes
  command:
    cmd: 'kubeadm token create --print-join-command'
  register: join_command

- name: Copying a join command
  local_action: copy content="{{join_command.stdout_lines[0]}} --cri-socket=unix:///var/run/cri-dockerd.sock" dest="/tmp/join-command"
