---

- hosts: k8s-nodes
  become: true
  pre_tasks: 

    - name: Update repositories
      apt:
        update_cache: true
      when:
        ansible_distribution in ['Debian']

  roles:
  - k8s-nodes
  tags: k8s-install

- hosts: master-nodes
  become: true
  roles:
  - master-nodes
  tags: k8s-init

- hosts: worker-nodes
  become: true
  roles:
  - worker-nodes
  tags: k8s-join
